# TODO: Оптимизируй Dockerfile.bad
# Найди все антипаттерны и исправь их:
# 1. Тег :latest
# 2. Порядок слоёв (кэширование)
# 3. Лишние команды
# 4. ADD vs COPY
# 5. Non-root user
# 6. CMD vs ENTRYPOINT
